# Generated by Django 4.2.1 on 2023-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('results', models.TextField()),
            ],
        ),
    ]
