# Generated by Django 4.2.1 on 2023-07-03 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('porcentaje', models.FloatField()),
                ('estado', models.CharField(max_length=255)),
                ('resultados', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='QueryResult',
        ),
    ]
